### ISSUE TITLE
Commercial Use

### ISSUE THREAD

**Issue by cafedeichi** [elliottbolzan/AdobeSign#1]
I was recently asked to find the way to implement hand-writing functions on a iPad application by my customer, and found your awesome example. Seemingly the Abobe Sign implementation looks very easy, however, i have to think how to publish the Abobe Sign embeded app for commercial use and provide it without user's login by its Abobe account. Is it possible to do that?
I'm afraid I know this question should be asked to Abobe directly, but I'm sure you know well the way I'd like to know. Hoping your friendly quick response.

**Comment by elliottbolzan** [comment]
Hi, and thank you for your kind words. I have not worked with Adobe Sign in a few months, but it is my understanding that at one point, you're going to need to make a user login with their Adobe Sign account. Unfortunately, the process of uploading a transient document and sending it out for signatures is tied to being logged in, if I remember correctly. That being said, I could be restricting the Adobe Sign API to the usage I made of it, and I think the best way for you to check is to go through the REST API endpoints you are interested in. If you're able to use the same oauth token indefinitely, you might be able to eliminate the login process on the iPad.

**Comment by cafedeichi** [comment]
Hi! Thx a lot your explicit answer. You reminded me of the existence of REST APIs. I'm gonna look through the feasibility of the implementaion that i want to do.
